name = "emanual-publish-api"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = true

[vars]
GH_OWNER = "hinjai2008"
GH_REPO = "emanual_CI"
GH_WORKFLOW_FILE = "content-build-handoff.yml"
GH_REF = "main"
# For strict security, set your app origin instead of *
ALLOWED_ORIGIN = "*"
 